### ISSUE TITLE
New project name, please?

### ISSUE THREAD

**Issue by awoods** [anqit/spanqit#1]
This looks like the start of a great project (it would be very helpful if it included SPARQL-Update). But with the name `spanqit`, use of this utility may be a non-starter.

**Comment by anqit** [comment]
Hi there, thanks for the feedback! Sorry for the late reply, but I've been out of the country and unfortunately inactive on the project. I have a few features I would like to add soon, and support for the rest of the remaining unimplemented SPARQL query types is high on that list! In the mean time, if you'd like to fork and try contributing the SPARQL Update query functionality yourself, the help would be much appreciated!

As for the project name, it's a jovial portmanteau of my name and SPARQL itself. I think it's harmless enough, and in fact, when pronounced correctly, doesn't resemble what you probably think it does (the 'a' is more of a 'u' sound) ;)

Thanks again!

**Comment by anqit** [comment]
@awoods I know it's been a while since you created this issue, but I've finally released a new version supporting SPARQL Update queries!

**Comment by awoods** [comment]
Thanks, @anqit . I will continue to keep this tool in-mind.
